### ISSUE TITLE
Respect the dest argument

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-login-logout#13]
e.g. in `/login?dest=%2Fcms%2F06786a92-44db-11e5-b3b2-1672f710807b.html`

(m.ft.com uses these kinds of URLs)

**Comment by matthew-andrews** [comment]
right now you end up on the home page if you hit that when logged in

**Comment by phamann** [comment]
Resolved by @matthew-andrews but issue it now moved to edge/routing layer as we require the `Referrer` header to remain in tact.
